[application]
name = "dioxus-class-demo"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Emoji Browser"

[web.watcher]
watch_path = ["src", "assets"]
reload_html = true

index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["assets/css/tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]
# serve: [dev-server] only

# [application.tools]

# use binaryen.wasm-opt for output Wasm file
# binaryen just will trigger in `web` platform
# binaryen = { wasm_opt = true }
